//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.30 at 11:53:15 AM ICT 
//


package net.serialisation.data;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.serialisation.data package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Catalog_QNAME = new QName("urn:data.serialisation.net", "catalog");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.serialisation.data
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CatalogData }
     * 
     */
    public CatalogData createCatalogData() {
        return new CatalogData();
    }

    /**
     * Create an instance of {@link Bookdata }
     * 
     */
    public Bookdata createBookdata() {
        return new Bookdata();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CatalogData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:data.serialisation.net", name = "catalog")
    public JAXBElement<CatalogData> createCatalog(CatalogData value) {
        return new JAXBElement<CatalogData>(_Catalog_QNAME, CatalogData.class, null, value);
    }

}
