
package net.mail.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MyOwnMailAgent", targetNamespace = "http://service.ws.mail.net/", wsdlLocation = "http://localhost:8080/gmailws/services/mail?wsdl")
public class MyOwnMailAgent
    extends Service
{

    private final static URL MYOWNMAILAGENT_WSDL_LOCATION;
    private final static WebServiceException MYOWNMAILAGENT_EXCEPTION;
    private final static QName MYOWNMAILAGENT_QNAME = new QName("http://service.ws.mail.net/", "MyOwnMailAgent");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/gmailws/services/mail?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MYOWNMAILAGENT_WSDL_LOCATION = url;
        MYOWNMAILAGENT_EXCEPTION = e;
    }

    public MyOwnMailAgent() {
        super(__getWsdlLocation(), MYOWNMAILAGENT_QNAME);
    }

    public MyOwnMailAgent(WebServiceFeature... features) {
        super(__getWsdlLocation(), MYOWNMAILAGENT_QNAME, features);
    }

    public MyOwnMailAgent(URL wsdlLocation) {
        super(wsdlLocation, MYOWNMAILAGENT_QNAME);
    }

    public MyOwnMailAgent(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MYOWNMAILAGENT_QNAME, features);
    }

    public MyOwnMailAgent(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MyOwnMailAgent(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSMail
     */
    @WebEndpoint(name = "WSMailImplPort")
    public WSMail getWSMailImplPort() {
        return super.getPort(new QName("http://service.ws.mail.net/", "WSMailImplPort"), WSMail.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSMail
     */
    @WebEndpoint(name = "WSMailImplPort")
    public WSMail getWSMailImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.ws.mail.net/", "WSMailImplPort"), WSMail.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MYOWNMAILAGENT_EXCEPTION!= null) {
            throw MYOWNMAILAGENT_EXCEPTION;
        }
        return MYOWNMAILAGENT_WSDL_LOCATION;
    }

}
